version: "3"

services:
  db:
    image: mariadb
    container_name: inkorea_db
    # command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    command: mysqld --console
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      # - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/initdb.d/db_tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/initdb.d/db_population.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: inkorea_db
      MYSQL_USER: mod
      MYSQL_PASSWORD: inkorea
      MYSQL_ROOT_PASSWORD: ego5Eek~
      VIRTUAL_HOST: www.db.inkorea.co, db.inkorea.co
      VIRTUAL_PORT: 3306
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: www.db.inkorea.co, db.inkorea.co
      LANG: C.UTF-8

    networks:
      - dbms_network
      - nginx-proxy
    restart: always
  phpmyadmin:
    container_name: studyboard_phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3030:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ego5Eek~
      VIRTUAL_HOST: www.db.inkorea.co, db.inkorea.co
      VIRTUAL_PORT: 3030
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: www.db.inkorea.co, db.inkorea.co
    networks:
      - dbms_network
      - nginx-proxy
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

networks:
  dbms_network:
    external: true
  nginx-proxy:
    external: true
