version: "3"

services:
  db:
    container_name: inkorea_db
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      # - ./db/initdb.d/db_tables.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./db/initdb.d/db_population.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      TZ: Asia/Seoul
      MYSQL_DATABASE: inkorea_db
      MYSQL_USER: mod
      MYSQL_PASSWORD: inkorea
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dbms_network
    restart: always
  phpmyadmin:
    container_name: myphpadmin_container
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dbms_network
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

networks:
  dbms_network:
    external: true
