version: "3"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 9090
    volumes:
      - .:/code
    ports:
      - "9090:9090"
    environment:
      TZ: Asia/Seoul
    networks:
      - dbms_network

networks:
  dbms_network:
    external: true
